name: GRNs
channels:
  - conda-forge
  - defaults
dependencies:
  - blas
  - bottleneck
  - brotli
  - brotli-bin
  - ca-certificates
  - colorama
  - contourpy
  - cycler
  - fonttools
  - freetype
  - importlib_resources
  - joblib
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libllvm14
  - libopenblas
  - libpng
  - libtiff
  - libwebp-base
  - llvm-openmp
  - llvmlite
  - lz4-c
  - matplotlib
  - matplotlib-base
  - ncurses
  - numba
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pillow
  - pip
  - pynndescent
  - pyparsing
  - python=3.9.19
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - readline
  - scikit-learn
  - scipy
  - setuptools
  - six
  - sqlite
  - tbb
  - threadpoolctl
  - tk
  - tornado
  - tqdm
  - tslearn
  - tzdata
  - umap-learn
  - unicodedata2
  - wheel
  - xz
  - zipp
  - zlib
  - zstd
  - pip:
    - absl-py
    - addict
    - autodiscjax
    - chex
    - equinox
    - importlib-metadata
    - jax
    - jaxlib
    - jaxtyping
    - ml-dtypes
    - opt-einsum
    - optax
    - python-libsbml
    - sbmltoodejax
    - sbmltoodepy
    - toolz
    - typeguard
    - typing-extensions
